language: c

sudo: false

dist: bionic

addons:
  apt:
    packages:
    - texlive
    - texlive-latex-extra
    - texlive-bibtex-extra
    - texlive-generic-extra
    - texlive-science
    - texlive-luatex
    - texlive-lang-greek
    - lmodern
    - biber
    - gnuplot-nox
    - wget
    - curl
    - sed
    - grep
    - python
    - python-pygments
    - aspell
    - aspell-en

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: deploy
  on:
    branch: master

env:
  - EXCLUDE_REWRITING=1  SED_REP='s/\\def\\excludefiles{}/\\def\\excludefiles{rewriting}/g'
  - EXCLUDE_REWRITING="" SED_REP='s/\\def\\excludefiles{rewriting}/\\def\\excludefiles{}/g'

before_script:
  - make ubuntu-deps
  - sed "${SED_REP}" -i jgross-thesis.tex

script:
  - make OTHERFLAGS="-interaction=nonstopmode"
  - make full-todo
  - make todo.svg full-todo.svg

after_success:
  - make deploy
