language: c

sudo: false

dist: bionic

addons:
  apt:
    packages:
    - texlive
    - texlive-latex-extra
    - texlive-bibtex-extra
    - texlive-generic-extra
    - texlive-science
    - texlive-luatex
    - texlive-lang-greek
    - lmodern
    - biber
    - gnuplot-nox
    - wget
    - curl
    - sed
    - grep
    - python
    - python-pygments

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: deploy
  on:
    branch: master

jobs:
  include:
    - env: EXCLUDE_REWRITING=1
      script: sed s'/\\def\\excludefiles{}/\\def\\excludefiles{rewriting}/g' -i jgross-thesis.tex && make OTHERFLAGS="-interaction=nonstopmode" && make todo && make todo.svg # this is the fast job, which exlcudes all the plots in rewriting
    - env: EXCLUDE_REWRITING=""
      script: sed s'/\\def\\excludefiles{rewriting}/\\def\\excludefiles{}/g' -i jgross-thesis.tex && make OTHERFLAGS="-interaction=nonstopmode" && make todo && make todo.svg

after_success:
  - make deploy
