language: c

sudo: false

addons:
  apt:
    packages:
    - texlive
    - texlive-latex-extra
    - texlive-bibtex-extra
    - texlive-science
    - wget
    - curl
    - sed
    - grep

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: deploy
  on:
    branch: master

script: make OTHERFLAGS="-interaction=nonstopmode" && make todo && make todo.svg

after_success:
  - mkdir -p deploy/nightly
  - cp -f jgross-thesis-proposal.pdf jgross-thesis.pdf todo.svg deploy/nightly/
