REWRITING_PERF_DATA := \
	rewriting/perf-LiftLetsMap-Rewrite-for.txt \
	rewriting/perf-LiftLetsMap-cps+vm-compute.txt \
	rewriting/perf-LiftLetsMap-rewrite-strat(bottomup,bottomup).txt \
	rewriting/perf-LiftLetsMap-rewrite-strat(topdown,bottomup).txt \
	rewriting/perf-LiftLetsMap-rewriting-(vm-only).txt \
	rewriting/perf-LiftLetsMap-rewriting.txt \
	rewriting/perf-LiftLetsMap-setoid-rewrite.txt \
	rewriting/perf-Plus0Tree+29-Rewrite-for.txt \
	rewriting/perf-Plus0Tree+29-cbv\;rewrite!.txt \
	rewriting/perf-Plus0Tree+29-cbv\;rewrite-strat(bottomup).txt \
	rewriting/perf-Plus0Tree+29-cbv\;rewrite-strat(topdown).txt \
	rewriting/perf-Plus0Tree+29-cbv\;setoid-rewrite.txt \
	rewriting/perf-Plus0Tree+29-rewriting-(vm-only).txt \
	rewriting/perf-Plus0Tree+29-rewriting.txt \
	rewriting/perf-Plus0Tree-Rewrite-for.txt \
	rewriting/perf-Plus0Tree-cbv\;rewrite!.txt \
	rewriting/perf-Plus0Tree-cbv\;rewrite-strat(bottomup).txt \
	rewriting/perf-Plus0Tree-cbv\;rewrite-strat(topdown).txt \
	rewriting/perf-Plus0Tree-cbv\;setoid-rewrite.txt \
	rewriting/perf-Plus0Tree-only-m-1-Rewrite-for.txt \
	rewriting/perf-Plus0Tree-only-m-1-cbv\;rewrite!.txt \
	rewriting/perf-Plus0Tree-only-m-1-cbv\;rewrite-strat(bottomup).txt \
	rewriting/perf-Plus0Tree-only-m-1-cbv\;rewrite-strat(topdown).txt \
	rewriting/perf-Plus0Tree-only-m-1-cbv\;setoid-rewrite.txt \
	rewriting/perf-Plus0Tree-only-m-1-rewriting-(vm-only).txt \
	rewriting/perf-Plus0Tree-only-m-1-rewriting.txt \
	rewriting/perf-Plus0Tree-only-m-2-Rewrite-for.txt \
	rewriting/perf-Plus0Tree-only-m-2-cbv\;rewrite!.txt \
	rewriting/perf-Plus0Tree-only-m-2-cbv\;rewrite-strat(bottomup).txt \
	rewriting/perf-Plus0Tree-only-m-2-cbv\;rewrite-strat(topdown).txt \
	rewriting/perf-Plus0Tree-only-m-2-cbv\;setoid-rewrite.txt \
	rewriting/perf-Plus0Tree-only-m-2-rewriting-(vm-only).txt \
	rewriting/perf-Plus0Tree-only-m-2-rewriting.txt \
	rewriting/perf-Plus0Tree-only-m-3-Rewrite-for.txt \
	rewriting/perf-Plus0Tree-only-m-3-cbv\;rewrite!.txt \
	rewriting/perf-Plus0Tree-only-m-3-cbv\;rewrite-strat(bottomup).txt \
	rewriting/perf-Plus0Tree-only-m-3-cbv\;rewrite-strat(topdown).txt \
	rewriting/perf-Plus0Tree-only-m-3-cbv\;setoid-rewrite.txt \
	rewriting/perf-Plus0Tree-only-m-3-rewriting-(vm-only).txt \
	rewriting/perf-Plus0Tree-only-m-3-rewriting.txt \
	rewriting/perf-Plus0Tree-only-n-1-Rewrite-for.txt \
	rewriting/perf-Plus0Tree-only-n-1-cbv\;rewrite!.txt \
	rewriting/perf-Plus0Tree-only-n-1-cbv\;rewrite-strat(bottomup).txt \
	rewriting/perf-Plus0Tree-only-n-1-cbv\;rewrite-strat(topdown).txt \
	rewriting/perf-Plus0Tree-only-n-1-cbv\;setoid-rewrite.txt \
	rewriting/perf-Plus0Tree-only-n-1-rewriting-(vm-only).txt \
	rewriting/perf-Plus0Tree-only-n-1-rewriting.txt \
	rewriting/perf-Plus0Tree-only-n-2-Rewrite-for.txt \
	rewriting/perf-Plus0Tree-only-n-2-cbv\;rewrite!.txt \
	rewriting/perf-Plus0Tree-only-n-2-cbv\;rewrite-strat(bottomup).txt \
	rewriting/perf-Plus0Tree-only-n-2-cbv\;rewrite-strat(topdown).txt \
	rewriting/perf-Plus0Tree-only-n-2-cbv\;setoid-rewrite.txt \
	rewriting/perf-Plus0Tree-only-n-2-rewriting-(vm-only).txt \
	rewriting/perf-Plus0Tree-only-n-2-rewriting.txt \
	rewriting/perf-Plus0Tree-only-n-3-Rewrite-for.txt \
	rewriting/perf-Plus0Tree-only-n-3-cbv\;rewrite!.txt \
	rewriting/perf-Plus0Tree-only-n-3-cbv\;rewrite-strat(bottomup).txt \
	rewriting/perf-Plus0Tree-only-n-3-cbv\;rewrite-strat(topdown).txt \
	rewriting/perf-Plus0Tree-only-n-3-cbv\;setoid-rewrite.txt \
	rewriting/perf-Plus0Tree-only-n-3-rewriting-(vm-only).txt \
	rewriting/perf-Plus0Tree-only-n-3-rewriting.txt \
	rewriting/perf-Plus0Tree-only-n-4-Rewrite-for.txt \
	rewriting/perf-Plus0Tree-only-n-4-cbv\;rewrite!.txt \
	rewriting/perf-Plus0Tree-only-n-4-cbv\;rewrite-strat(bottomup).txt \
	rewriting/perf-Plus0Tree-only-n-4-cbv\;rewrite-strat(topdown).txt \
	rewriting/perf-Plus0Tree-only-n-4-cbv\;setoid-rewrite.txt \
	rewriting/perf-Plus0Tree-only-n-4-rewriting-(vm-only).txt \
	rewriting/perf-Plus0Tree-only-n-4-rewriting.txt \
	rewriting/perf-Plus0Tree-only-n-5-Rewrite-for.txt \
	rewriting/perf-Plus0Tree-only-n-5-cbv\;rewrite!.txt \
	rewriting/perf-Plus0Tree-only-n-5-cbv\;rewrite-strat(bottomup).txt \
	rewriting/perf-Plus0Tree-only-n-5-cbv\;rewrite-strat(topdown).txt \
	rewriting/perf-Plus0Tree-only-n-5-cbv\;setoid-rewrite.txt \
	rewriting/perf-Plus0Tree-only-n-5-rewriting-(vm-only).txt \
	rewriting/perf-Plus0Tree-only-n-5-rewriting.txt \
	rewriting/perf-Plus0Tree-only-n-6-Rewrite-for.txt \
	rewriting/perf-Plus0Tree-only-n-6-cbv\;rewrite!.txt \
	rewriting/perf-Plus0Tree-only-n-6-cbv\;rewrite-strat(bottomup).txt \
	rewriting/perf-Plus0Tree-only-n-6-cbv\;rewrite-strat(topdown).txt \
	rewriting/perf-Plus0Tree-only-n-6-cbv\;setoid-rewrite.txt \
	rewriting/perf-Plus0Tree-only-n-6-rewriting-(vm-only).txt \
	rewriting/perf-Plus0Tree-only-n-6-rewriting.txt \
	rewriting/perf-Plus0Tree-only-n-7-Rewrite-for.txt \
	rewriting/perf-Plus0Tree-only-n-7-cbv\;rewrite!.txt \
	rewriting/perf-Plus0Tree-only-n-7-cbv\;rewrite-strat(bottomup).txt \
	rewriting/perf-Plus0Tree-only-n-7-cbv\;rewrite-strat(topdown).txt \
	rewriting/perf-Plus0Tree-only-n-7-cbv\;setoid-rewrite.txt \
	rewriting/perf-Plus0Tree-only-n-7-rewriting-(vm-only).txt \
	rewriting/perf-Plus0Tree-only-n-7-rewriting.txt \
	rewriting/perf-Plus0Tree-only-n-8-Rewrite-for.txt \
	rewriting/perf-Plus0Tree-only-n-8-cbv\;rewrite!.txt \
	rewriting/perf-Plus0Tree-only-n-8-cbv\;rewrite-strat(bottomup).txt \
	rewriting/perf-Plus0Tree-only-n-8-cbv\;rewrite-strat(topdown).txt \
	rewriting/perf-Plus0Tree-only-n-8-cbv\;setoid-rewrite.txt \
	rewriting/perf-Plus0Tree-only-n-8-rewriting-(vm-only).txt \
	rewriting/perf-Plus0Tree-only-n-8-rewriting.txt \
	rewriting/perf-Plus0Tree-only-n-9-Rewrite-for.txt \
	rewriting/perf-Plus0Tree-only-n-9-cbv\;rewrite!.txt \
	rewriting/perf-Plus0Tree-only-n-9-cbv\;rewrite-strat(bottomup).txt \
	rewriting/perf-Plus0Tree-only-n-9-cbv\;rewrite-strat(topdown).txt \
	rewriting/perf-Plus0Tree-only-n-9-cbv\;setoid-rewrite.txt \
	rewriting/perf-Plus0Tree-only-n-9-rewriting-(vm-only).txt \
	rewriting/perf-Plus0Tree-only-n-9-rewriting.txt \
	rewriting/perf-Plus0Tree-rewriting-(vm-only).txt \
	rewriting/perf-Plus0Tree-rewriting.txt \
	rewriting/perf-SieveOfEratosthenes-Rewrite-for.txt \
	rewriting/perf-SieveOfEratosthenes-cbn.txt \
	rewriting/perf-SieveOfEratosthenes-cbv.txt \
	rewriting/perf-SieveOfEratosthenes-lazy.txt \
	rewriting/perf-SieveOfEratosthenes-native(1)(real).txt \
	rewriting/perf-SieveOfEratosthenes-native(2)(real).txt \
	rewriting/perf-SieveOfEratosthenes-rewriting-(vm-only).txt \
	rewriting/perf-SieveOfEratosthenes-rewriting.txt \
	rewriting/perf-SieveOfEratosthenes-simpl.txt \
	rewriting/perf-SieveOfEratosthenes-vm-compute.txt \
	rewriting/perf-UnderLetsPlus0-Rewrite-for.txt \
	rewriting/perf-UnderLetsPlus0-cbv\;rewrite-strat(bottomup).txt \
	rewriting/perf-UnderLetsPlus0-cbv\;rewrite-strat(topdown).txt \
	rewriting/perf-UnderLetsPlus0-cbv\;setoid-rewrite.txt \
	rewriting/perf-UnderLetsPlus0-rewriting-(vm-only).txt \
	rewriting/perf-UnderLetsPlus0-rewriting.txt \
	rewriting/perf-new-extraction-over-new-extraction--only-UnsaturatedSolinas-x32.txt \
	rewriting/perf-new-extraction-over-new-extraction--only-UnsaturatedSolinas-x64.txt \
	rewriting/perf-new-extraction-over-new-extraction--only-WordByWordMontgomery-x32.txt \
	rewriting/perf-new-extraction-over-new-extraction--only-WordByWordMontgomery-x64.txt \
	rewriting/perf-new-extraction-over-new-extraction.txt \
	rewriting/perf-new-extraction-over-old-vm--only-UnsaturatedSolinas-x32.txt \
	rewriting/perf-new-extraction-over-old-vm--only-UnsaturatedSolinas-x64.txt \
	rewriting/perf-new-extraction-over-old-vm--only-WordByWordMontgomery-x32.txt \
	rewriting/perf-new-extraction-over-old-vm--only-WordByWordMontgomery-x64.txt \
	rewriting/perf-new-extraction-over-old-vm.txt \
	rewriting/perf-new-extraction-times--only-UnsaturatedSolinas-x32.txt \
	rewriting/perf-new-extraction-times--only-UnsaturatedSolinas-x64.txt \
	rewriting/perf-new-extraction-times--only-WordByWordMontgomery-x32.txt \
	rewriting/perf-new-extraction-times--only-WordByWordMontgomery-x64.txt \
	rewriting/perf-new-extraction-times.txt \
	rewriting/perf-new-vm-over-new-extraction--only-UnsaturatedSolinas-x32.txt \
	rewriting/perf-new-vm-over-new-extraction--only-UnsaturatedSolinas-x64.txt \
	rewriting/perf-new-vm-over-new-extraction--only-WordByWordMontgomery-x32.txt \
	rewriting/perf-new-vm-over-new-extraction--only-WordByWordMontgomery-x64.txt \
	rewriting/perf-new-vm-over-new-extraction.txt \
	rewriting/perf-new-vm-over-old-vm--only-UnsaturatedSolinas-x32.txt \
	rewriting/perf-new-vm-over-old-vm--only-UnsaturatedSolinas-x64.txt \
	rewriting/perf-new-vm-over-old-vm--only-WordByWordMontgomery-x32.txt \
	rewriting/perf-new-vm-over-old-vm--only-WordByWordMontgomery-x64.txt \
	rewriting/perf-new-vm-over-old-vm.txt \
	rewriting/perf-new-vm-times--only-UnsaturatedSolinas-x32.txt \
	rewriting/perf-new-vm-times--only-UnsaturatedSolinas-x64.txt \
	rewriting/perf-new-vm-times--only-WordByWordMontgomery-x32.txt \
	rewriting/perf-new-vm-times--only-WordByWordMontgomery-x64.txt \
	rewriting/perf-new-vm-times.txt \
	rewriting/perf-old-cbv-times--only-UnsaturatedSolinas-x32.txt \
	rewriting/perf-old-cbv-times--only-UnsaturatedSolinas-x64.txt \
	rewriting/perf-old-cbv-times--only-WordByWordMontgomery-x32.txt \
	rewriting/perf-old-cbv-times--only-WordByWordMontgomery-x64.txt \
	rewriting/perf-old-cbv-times.txt \
	rewriting/perf-old-vm-over-new-extraction--only-UnsaturatedSolinas-x32.txt \
	rewriting/perf-old-vm-over-new-extraction--only-UnsaturatedSolinas-x64.txt \
	rewriting/perf-old-vm-over-new-extraction--only-WordByWordMontgomery-x32.txt \
	rewriting/perf-old-vm-over-new-extraction--only-WordByWordMontgomery-x64.txt \
	rewriting/perf-old-vm-over-new-extraction.txt \
	rewriting/perf-old-vm-over-old-vm--only-UnsaturatedSolinas-x32.txt \
	rewriting/perf-old-vm-over-old-vm--only-UnsaturatedSolinas-x64.txt \
	rewriting/perf-old-vm-over-old-vm--only-WordByWordMontgomery-x32.txt \
	rewriting/perf-old-vm-over-old-vm--only-WordByWordMontgomery-x64.txt \
	rewriting/perf-old-vm-over-old-vm.txt \
	rewriting/perf-old-vm-times--only-UnsaturatedSolinas-x32.txt \
	rewriting/perf-old-vm-times--only-UnsaturatedSolinas-x64.txt \
	rewriting/perf-old-vm-times--only-WordByWordMontgomery-x32.txt \
	rewriting/perf-old-vm-times--only-WordByWordMontgomery-x64.txt \
	rewriting/perf-old-vm-times.txt \
	#
